# -*- coding: utf-8 -*-
"""Python_hourly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ByNo9ylw1TQMdaEIKD2i1OKkf_cPabol
"""

import requests

url = "https://www.helioscope.com/api/simulations/8131309/hourly"

payload={}
headers = {
  'access_token': 'AjVPDLk1IskXnU4yQr8sthSCWY1Jt6',
}

response = requests.request("GET", url, headers=headers, data=payload)

with open('Helioscope.zip', "wb") as f:
    for chunk in response.iter_content(chunk_size=512):
        if chunk:  # filter out keep-alive new chunks
            f.write(chunk)

